-- 金豬食堂：付款後 LINE 綁定、Bot 查詢與取消申請
-- 原始一次性 token 不落庫，只保存 SHA-256 雜湊。

CREATE TABLE IF NOT EXISTS public.gold_pig_bookings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_no text NOT NULL UNIQUE,
  status text NOT NULL DEFAULT 'confirmed'
    CHECK (status IN ('confirmed', 'cancellation_requested', 'cancelled')),
  is_demo boolean NOT NULL DEFAULT false,
  session_date date NOT NULL,
  session_time time NOT NULL,
  tables_4 integer NOT NULL DEFAULT 0 CHECK (tables_4 >= 0 AND tables_4 <= 20),
  tables_6 integer NOT NULL DEFAULT 0 CHECK (tables_6 >= 0 AND tables_6 <= 20),
  guest_count integer NOT NULL CHECK (guest_count > 0 AND guest_count <= 120),
  total_amount integer NOT NULL CHECK (total_amount > 0),
  payment_method text,
  payment_reference text,
  contact_name text,
  contact_phone text,
  contact_email text,
  paid_at timestamptz NOT NULL,
  line_user_id text,
  line_bound_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT gold_pig_tables_present CHECK (tables_4 + tables_6 BETWEEN 1 AND 2)
);

CREATE TABLE IF NOT EXISTS public.gold_pig_booking_tokens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id bigint NOT NULL REFERENCES public.gold_pig_bookings(id) ON DELETE CASCADE,
  token_hash text NOT NULL UNIQUE CHECK (token_hash ~ '^[a-f0-9]{64}$'),
  expires_at timestamptz NOT NULL,
  used_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.gold_pig_cancellation_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id bigint NOT NULL REFERENCES public.gold_pig_bookings(id) ON DELETE CASCADE,
  line_user_id text NOT NULL,
  status text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'approved', 'rejected', 'withdrawn')),
  note text,
  created_at timestamptz NOT NULL DEFAULT now(),
  processed_at timestamptz
);

CREATE INDEX IF NOT EXISTS gold_pig_bookings_line_status_idx
  ON public.gold_pig_bookings (line_user_id, status, session_date)
  WHERE line_user_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS gold_pig_bookings_session_idx
  ON public.gold_pig_bookings (session_date, session_time, status);

CREATE INDEX IF NOT EXISTS gold_pig_booking_tokens_active_idx
  ON public.gold_pig_booking_tokens (expires_at, booking_id)
  WHERE used_at IS NULL;

CREATE INDEX IF NOT EXISTS gold_pig_booking_tokens_booking_idx
  ON public.gold_pig_booking_tokens (booking_id);

CREATE INDEX IF NOT EXISTS gold_pig_cancel_line_created_idx
  ON public.gold_pig_cancellation_requests (line_user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS gold_pig_cancel_booking_idx
  ON public.gold_pig_cancellation_requests (booking_id);

CREATE UNIQUE INDEX IF NOT EXISTS gold_pig_cancel_one_pending_idx
  ON public.gold_pig_cancellation_requests (booking_id)
  WHERE status = 'pending';

ALTER TABLE public.gold_pig_bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gold_pig_booking_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gold_pig_cancellation_requests ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.gold_pig_bookings FROM anon, authenticated;
REVOKE ALL ON TABLE public.gold_pig_booking_tokens FROM anon, authenticated;
REVOKE ALL ON TABLE public.gold_pig_cancellation_requests FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public.gold_pig_bookings_id_seq FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public.gold_pig_booking_tokens_id_seq FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public.gold_pig_cancellation_requests_id_seq FROM anon, authenticated;

GRANT ALL ON TABLE public.gold_pig_bookings TO service_role;
GRANT ALL ON TABLE public.gold_pig_booking_tokens TO service_role;
GRANT ALL ON TABLE public.gold_pig_cancellation_requests TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.gold_pig_bookings_id_seq TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.gold_pig_booking_tokens_id_seq TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.gold_pig_cancellation_requests_id_seq TO service_role;

DROP POLICY IF EXISTS gold_pig_bookings_service_all ON public.gold_pig_bookings;
CREATE POLICY gold_pig_bookings_service_all ON public.gold_pig_bookings
  FOR ALL TO service_role USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS gold_pig_tokens_service_all ON public.gold_pig_booking_tokens;
CREATE POLICY gold_pig_tokens_service_all ON public.gold_pig_booking_tokens
  FOR ALL TO service_role USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS gold_pig_cancellations_service_all ON public.gold_pig_cancellation_requests;
CREATE POLICY gold_pig_cancellations_service_all ON public.gold_pig_cancellation_requests
  FOR ALL TO service_role USING (true) WITH CHECK (true);

COMMENT ON TABLE public.gold_pig_bookings IS 'Asia Miles 金豬食堂活動訂位；由受信任付款後端建立。';
COMMENT ON TABLE public.gold_pig_booking_tokens IS '訂位 LINE 綁定的一次性 token 雜湊；不可保存原始 token。';
COMMENT ON TABLE public.gold_pig_cancellation_requests IS '由 LINE Bot 建立的取消申請；pending 不等於已取消或已退款。';
